### ISSUE TITLE
urllib3<2 is impacting library compatibility

### ISSUE THREAD

**Issue by jocado** [canonical/pylxd#600]
Hi,

Pinning `urllib3<2` is causing some compatibility issues with including pylxd as a dependency in some projects.  As it also forces `requests< 2.32.0` that has some un-patched CVE.

Is there any chance it can be can be updated to `urllib3>=2` ?

Thanks!

Cheers,
Just

**Comment by hamistao** [comment]
Pinning the `requests< 2.32.0` is unfortunately necessary for the moment because of https://github.com/msabramo/requests-unixsocket/pull/72.

It is in our current plans for the next version to [remove dependency on `requests_unixsocket`](https://github.com/canonical/pylxd/issues/583) for this exact reason. This enable us to update `urllib3` as you suggested.

We should have more news on this topic soon, cheers.

**Comment by simondeziel** [comment]
Fixed by #604
